### ISSUE TITLE
On the server side, after running npm run start:dev, an error is reported

### ISSUE THREAD

**Issue by yangzuocheng** [falcofemoralis/freemap#33]
On the server side, after running npm run start:dev, an error is reported

`[11:41:24] Starting compilation in watch mode...

DeprecationWarning: 'getMutableClone' has been deprecated since v4.0.0. Use an appropriate `factory.update...` method instead, use `setCommentRange` or `setSourceMapRange`, and avoid setting `parent`.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
src/modules/map/map.service.ts:45:7 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(path: string | string[], select?: any, model?: string | Model<any, {}, {}, {}, any>, match?: any): Query<(Omit<Document<unknown, any, MapFeatureDocument> & Omit<...>, keyof MapFeature> & MapFeature)[], Document<...> & Omit<...>, {}, Omit<...> & MapFeature>', gave the following error.
    Argument of type '{ path: string; populate: ({ path: string; model: typeof Category; select: string; } | { path: string; model: typeof User; select: string; })[]; }' is not assignable to parameter of type 'string | string[]'.
      Object literal may only specify known properties, and 'path' does not exist in type 'string[]'.

45       path: 'properties',
         ~~~~~~~~~~~~~~~~~~


src/modules/map/map.service.ts:101:7 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(path: string | string[], select?: any, model?: string | Model<any, {}, {}, {}, any>, match?: any): Query<Omit<Document<unknown, any, MapFeatureDocument> & Omit<...>, keyof MapFeature> & MapFeature, Document<...> & Omit<...>, {}, Omit<...> & MapFeature>', gave the following error.
    Argument of type '{ path: string; populate: ({ path: string; model: typeof Category; select: string; } | { path: string; model: typeof User; select: string; } | { path: string; model: typeof UserComment; })[]; }' is not assignable to parameter of type 'string | string[]'.
      Object literal may only specify known properties, and 'path' does not exist in type 'string[]'.

101       path: 'properties',
          ~~~~~~~~~~~~~~~~~~

src/modules/map/map.service.ts:159:9 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(path: string | string[], select?: any, model?: string | Model<any, {}, {}, {}, any>, match?: any): Query<(Omit<Document<unknown, any, MapFeatureDocument> & Omit<...>, keyof MapFeature> & MapFeature)[], Document<...> & Omit<...>, {}, Omit<...> & MapFeature>', gave the following error.
    Argument of type '{ path: string; populate: ({ path: string; model: typeof FeatureType; } | { path: string; model: typeof Category; select: string; } | { path: string; model: typeof User; select: string; })[]; }' is not assignable to parameter of type 'string | string[]'.
      Object literal may only specify known properties, and 'path' does not exist in type 'string[]'.

159         path: 'properties',
            ~~~~~~~~~~~~~~~~~~


[11:41:28] Found 3 errors. Watching for file changes.`

**Comment by falcofemoralis** [comment]
why do you want to run this repo? :)

p.s cloned, npm i, npm run start:dev, no errors for me

**Comment by yangzuocheng** [comment]
First, although I didn't start this project, I knew it was cool.
I wanted to learn and see, I just ran it. start.bat should be after node_modules is installed on the client and server. Start their respective services. As you can see, the client can start normally. It seems that only env_example needs to fill in the token. But I don’t know what to fill in for server’s env_example. In fact, a Google token is necessary? Or is it necessary? Frankly, I'm a little overwhelmed.
at last. Thank you for your answer.

**Comment by falcofemoralis** [comment]
ok, I barely found all my tokens to start this project, so I uploaded them, can try to start :)

**Comment by yangzuocheng** [comment]
Are you unable to start this project? This is such a shame. Anyway, thank you

**Comment by falcofemoralis** [comment]
I just started it, everything works as expected (at least from quck view)

**Comment by panzhiyue** [comment]
@yangzuocheng 你好，我有事想联系你一下你，但是你没有公开邮箱号，看到了可以联系一下我吗，我的邮箱是892105346@qq.com
